<a href="https://colab.research.google.com/github/mayurasandakalum/tensorflow-practice-1/blob/main/prac_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow

In [3]:
import tensorflow as tf
from tensorflow import keras
from keras.layers import Dense
from keras.models import Sequential, load_model
from tensorflow.keras.datasets import mnist

In [4]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

print(x_train.shape)
print(y_train.shape)

11490434/11490434 [==============================] - 2s 0us/step
(60000, 28, 28)
(60000,)


In [5]:
x_train = x_train.reshape(-1, 28 * 28).astype("float32") / 255.0
x_test = x_test.reshape(-1, 28 * 28).astype("float32") / 255.0

print(x_train)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [6]:
def createModel():
  model = keras.Sequential()
  model.add(keras.Input(shape=28*28))
  model.add(Dense(512, activation='relu'))
  model.add(Dense(256, activation='relu'))
  model.add(Dense(10))

  return model

In [7]:
myModel = createModel()
print(myModel.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 512)               401920    
                                                                 
 dense_1 (Dense)             (None, 256)               131328    
                                                                 
 dense_2 (Dense)             (None, 10)                2570      
                                                                 
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________
None


In [10]:
myModel.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    metrics=["accuracy"],
)

myModel.fit(x_train, y_train, batch_size=32, epochs=5, verbose=2)
myModel.evaluate(x_test, y_test, batch_size=32, verbose=2)

Epoch 1/5
1875/1875 - 5s - loss: 0.0189 - accuracy: 0.9944 - 5s/epoch - 3ms/step
Epoch 2/5
1875/1875 - 4s - loss: 0.0166 - accuracy: 0.9950 - 4s/epoch - 2ms/step
Epoch 3/5
1875/1875 - 5s - loss: 0.0146 - accuracy: 0.9959 - 5s/epoch - 2ms/step
Epoch 4/5
1875/1875 - 4s - loss: 0.0143 - accuracy: 0.9959 - 4s/epoch - 2ms/step
Epoch 5/5
1875/1875 - 4s - loss: 0.0125 - accuracy: 0.9963 - 4s/epoch - 2ms/step
313/313 - 1s - loss: 0.1173 - accuracy: 0.9814 - 638ms/epoch - 2ms/step


[0.11731800436973572, 0.9814000129699707]