<a href="https://colab.research.google.com/github/mayurasandakalum/tensorflow-practice-1/blob/main/prac_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import os

In [ ]:
x = tf.constant([0, 10, 15, 20, 30, 10, 20, 30])
print(x)
print(x[:])
print(x[1:])
print(x[0:4])
print(x[::2])
print(x[::-1])

tf.Tensor([ 0 10 15 20 30 10 20 30], shape=(8,), dtype=int32)
tf.Tensor([ 0 10 15 20 30 10 20 30], shape=(8,), dtype=int32)
tf.Tensor([10 15 20 30 10 20 30], shape=(7,), dtype=int32)
tf.Tensor([ 0 10 15 20], shape=(4,), dtype=int32)
tf.Tensor([ 0 15 30 20], shape=(4,), dtype=int32)
tf.Tensor([30 20 10 30 20 15 10  0], shape=(8,), dtype=int32)


 Indices

In [ ]:
x = tf.constant([[10, 20], [30, 40], [50, 60], [70, 80]])
indicesIndexes = tf.constant([0, 3])
print(indicesIndexes)

indexedTensor = tf.gather(x, indices=indicesIndexes)
print(indexedTensor)

tf.Tensor([0 3], shape=(2,), dtype=int32)
tf.Tensor(
[[10 20]
 [70 80]], shape=(2, 2), dtype=int32)


Reshaping

In [ ]:
tensorA = tf.range(16)
print(tensorA)

x = tf.reshape(tensorA, (4, 4))
print(x)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15], shape=(16,), dtype=int32)
tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]], shape=(4, 4), dtype=int32)
