In [2]:
import tensorflow as tf

>Element wise addition

In [ ]:
tensorA = tf.constant([20, 6, 7])
tensorB = tf.constant([45, 7, 21])

tensorC = tf.add(tensorA, tensorB) #? or tensorC = tensorA + tensorB

print(tensorA)
print(tensorB)
print(tensorC)

>Element wise substraction

In [ ]:
tensorC = tf.subtract(tensorA, tensorB) #? or tensorC = tensorA - tensorB
print(tensorC)

> Element wise division

In [ ]:
tensorD = tf.divide(tensorA, tensorB) #? or tensorC = tensorA / tensorB
print(tensorD)

> Tensor multiplication

In [11]:
tensorE = tf.multiply(tensorA, tensorB)
print(tensorE)

tf.Tensor([900  42 147], shape=(3,), dtype=int32)


> Dot product

In [4]:
import numpy as np

tensorA = tf.constant(np.array([[1, 2], [3, 4]]))
tensorB = tf.constant(np.array([[11, 12], [13, 14]]))

#? [[*11 + 2*13], [1*12 + 2*14]], [[3*11 + 4*13], [3*12 + 4*14]]
tensorC = tf.tensordot(tensorA, tensorB, axes=1)

print(tensorA)
print(tensorB)
print(tensorC)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[11 12]
 [13 14]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[37 40]
 [85 92]], shape=(2, 2), dtype=int32)
